= Auto-scan docs and send them
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description
Auto-scan is a tool to automatically scan documents from HP, OCR files, optimize it and finally send it by email as attachment.

## Architectures

Based on python 3.6 slim buster it supports

* [x] `linux/386`
* [x] `linux/amd64`
* [x] `linux/arm/v5`
* [x] `linux/arm/v7`
* [x] `linux/arm64/v8`
* [x] `linux/ppc64le`
* [x] `linux/s390x`

== Prerequisites
In order to correctly work properly this script needs access to DBus. Actual shortcut is to run it as privileged Docker container and map host socket to gain access to DBus (see launch script below).

== How to getting started
Git clone actual repo:
```bash
git clone https://github.com/matbgn/auto-scan.git
```

Git Shallow Clone the scan-pdf repo adapted for HP scanners:
```bash
cd auto-scan
git clone --depth=1 https://github.com/matbgn/scan-pdf.git
```

Build docker image locally:
```dockerfile
docker build -t matbgn/auto_scan .
```


== Usage

Scanning mode supported:
```
# ADF|Duplex|Flatbed
SCAN_MODE=ADF
```

Run script:
```dockerfile
sudo docker run -it --rm --net=host --privileged \
-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
-e RPI_EMAIL=your_email@gmail.com \
-e RPI_PASS=your_gmail_app_secret \
-e EMAIL_RECIPIENTS="email1@gmail.com;email2@gmail.com" \
-e SCAN_MODE=ADF \
-e SUBJECT="Test scan" \
matbgn/auto_scan
```

== Development mode

Be sure to have those packages installed:

    sudo apt-get install -y sane-utils libsane-hpaio \
    imagemagick ocrmypdf \
    tesseract-ocr-fra tesseract-ocr-deu

Put your var in a .env file with above possibilities:

    RPI_EMAIL=your_email@gmail.com
    RPI_PASS=your_gmail_app_secret
    EMAIL_RECIPIENTS=""email1@gmail.com;email2@gmail.com"
    SCAN_MODE=ADF
    SUBJECT="Test scan"

(Run venv &) Install requirements with:

    pip install -r requirements.txt

Then run script directly with:

    python ./main.py
